// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zevnvdjscgyebmfvbxhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpldm52ZGpzY2d5ZWJtZnZieGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTA2NDQsImV4cCI6MjA1OTg4NjY0NH0.Vo9Iorq9MKx1JRW1KoJbGePQsm9vwnux9WaARftOtrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);